COMPONENT=GPSRTesterC
CFLAGS += -I ../../Neighborhood/src
CFLAGS += -I ../../GeometrySupport/src
CFLAGS += -I ../../BoundaryDetection/src
CFLAGS += -I ../../Identity/src
CFLAGS += -I$(TOSDIR)/lib/net \
          -I$(TOSDIR)/lib/net/drip
include $(MAKERULES)

